version: "3.7"

services:
  modelo-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME
      - HTTP_PORT
    volumes:
      - ../../ssl:/app/ssl
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    command: npm run start
    networks:
      - srvweb-network

networks:
  srvweb-network:
    driver: bridge
