version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ganttly_db
    environment:
      POSTGRES_USER: postgres # Substitua pelo nome de usuário desejado
      POSTGRES_PASSWORD: postgres # Substitua pela senha desejada
      POSTGRES_DB: ganttly_db # Substitua pelo nome do banco de dados desejado
    ports:
      - '2345:5432' # Mapeia a porta 5432 do container para a porta 5432 do host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência de dados

volumes:
  postgres_data:
    driver: local
